# Generated by Django 2.2.5 on 2019-10-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_last_login_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginmethod',
            name='provider_id',
            field=models.CharField(choices=[('axiell_aurora', 'axiell_aurora'), ('eduhelfi', 'eduhelfi'), ('espoo', 'espoo'), ('facebook', 'facebook'), ('github', 'github'), ('google', 'google'), ('helsinki_adfs', 'helsinki_adfs'), ('helsinki_library_asko_adfs', 'helsinki_library_asko_adfs'), ('suomifi', 'suomifi'), ('turku_adfs', 'turku_adfs'), ('turku_suomifi', 'turku_suomifi'), ('yletunnus', 'yletunnus')], max_length=50, unique=True),
        ),
    ]
