# Generated by Django 2.2.5 on 2019-10-21 06:09

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_allow_first_name_to_be_longer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginMethodTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name_t', models.CharField(max_length=100, verbose_name='name')),
                ('short_description_t', models.TextField(blank=True, null=True, verbose_name='short description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='users.LoginMethod')),
            ],
            options={
                'verbose_name': 'login method Translation',
                'db_table': 'users_loginmethod_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModel, models.Model),
        ),
    ]
