# Generated by Django 2.2.5 on 2019-10-21 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_migrate_login_method_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginmethod',
            name='name',
        ),
        migrations.RemoveField(
            model_name='loginmethod',
            name='short_description',
        ),
        migrations.RenameField(
            model_name='loginmethodtranslation',
            old_name='name_t',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='loginmethodtranslation',
            old_name='short_description_t',
            new_name='short_description',
        ),
    ]
