# Generated by Django 2.2.5 on 2019-10-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_finish_login_method_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginmethod',
            name='require_registered_client',
            field=models.BooleanField(default=False, help_text='Set if this login method is not allowed when the login flow is started without an OIDC client', verbose_name='require registered client'),
        ),
    ]
